### ISSUE TITLE
Thanks for using Element Plus 😘

### ISSUE THREAD

**Issue by zazzaz** [MangoTsing/vite-electron-quick#1]
Element Plus is still under heavy development. Feel free to ask us anything if needed.

https://github.com/element-plus/element-plus/issues/new

**Comment by MangoTsing** [comment]
> Element Plus is still under heavy development. Feel free to ask us anything if needed.
> 
> https://github.com/element-plus/element-plus/issues/new

Thank you also for your efforts 😄
