### ISSUE TITLE
打包出来有问题

### ISSUE THREAD

**Issue by yigehaobb** [MangoTsing/vite-electron-quick#3]
Not allowed to load local resource: file:///C:/Users/Bo/Desktop/vite-electron-quick-master/vite-electron-quick-master/dist/win-unpacked/resources/app.asar/dist/render/index.html
 之前vite1 打包出来没问题

**Comment by MangoTsing** [comment]
Vite2 升级之后，配置项有所变更，涉及 build.base 以及 build.outDIr 等参数的问题已处理，重新拉取一下，应该可以打包跑起来了。

**Comment by yigehaobb** [comment]
可以打包成功了 还有个小问题，dev时候可以reload重载到首页  build打包出来reload就白屏了

**Comment by MangoTsing** [comment]
> 可以打包成功了 还有个小问题，dev时候可以reload重载到首页 build打包出来reload就白屏了

刷新问题通过更改 vue-router 的 history mode 已经修正，顺便缩小了一下打包体积。（按理说这个 reload 白屏问题应该一直都存在，但是没发现😂）

**Comment by yigehaobb** [comment]
嗯嗯  现在好了 谢谢大佬 
那个dev模式警告 可以 在main.ts里面 加  process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true'

**Comment by yigehaobb** [comment]
最新的dev 挺快的 修改后反应也很快

**Comment by MangoTsing** [comment]
> 嗯嗯 现在好了 谢谢大佬
> 那个dev模式警告 可以 在main.ts里面 加 process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true'

ok，我之后看一下，不是大佬，打工人罢了/(ㄒoㄒ)/~~
