### ISSUE TITLE
升级最新依赖出错

### ISSUE THREAD

**Issue by yigehaobb** [MangoTsing/vite-electron-quick#5]
升级到最新依赖 然后dev 报错
[vue] (!) "build.base" config option is deprecated. "base" is now a root-level config option.
[vue] (!) invalid "base" option: .. The value can only be an absolute URL, ./, or an empty string.
大佬有空看下不 谢谢

**Comment by MangoTsing** [comment]
https://github.com/vitejs/vite/compare/v2.0.0-beta.37...v2.0.0-beta.38

1月23日的一次更新将 build.base 移动到配置文件根级别，所以需要稍微修改一下，可以看我新增提交👌

**Comment by yigehaobb** [comment]
大佬真及时，我才刚找到是vite升级带来的问题

**Comment by yigehaobb** [comment]
更新后dev 运行错误  提示是  index.vue和main.ts 不能 require  electron

**Comment by MangoTsing** [comment]
> 更新后dev 运行错误 提示是 index.vue和main.ts 不能 require electron

没有发现这个问题，可以给我个复现方式

**Comment by yigehaobb** [comment]
![1111](https://user-images.githubusercontent.com/8196320/105799115-b8026b00-5fce-11eb-8bb7-dba9217ac004.jpg)
![2222](https://user-images.githubusercontent.com/8196320/105799125-bc2e8880-5fce-11eb-95dc-9216e5f31225.jpg)
我重新下载最新的只yarn 和yarn dev 没升级其他依赖 还是一样不行

**Comment by MangoTsing** [comment]
> ![1111](https://user-images.githubusercontent.com/8196320/105799115-b8026b00-5fce-11eb-8bb7-dba9217ac004.jpg)
> ![2222](https://user-images.githubusercontent.com/8196320/105799125-bc2e8880-5fce-11eb-95dc-9216e5f31225.jpg)
> 我重新下载最新的只yarn 和yarn dev 没升级其他依赖 还是一样不行

别直接访问url，在electron客户端里访问，yarn dev 之后应该会弹出窗口

**Comment by yigehaobb** [comment]
yarn dev 之后 没出现 electron 客户端

**Comment by MangoTsing** [comment]
> 就是yarn dev 之后 没出现 electron 客户端 不然也不会用浏览器访问的 额 要不我就先用vite 老版本的

这个问题我看了一下，先改成 tcp 轮询可以正常使用，vite2 暂时不知道为什么会在启动之后，通过 http请求 返回一个 404 状态导致开发模式的时候没办法回调。

**Comment by MangoTsing** [comment]
> > 就是yarn dev 之后 没出现 electron 客户端 不然也不会用浏览器访问的 额 要不我就先用vite 老版本的
> 
> 这个问题我看了一下，先改成 tcp 轮询可以正常使用，vite2 暂时不知道为什么会在启动之后，通过 http请求 返回一个 404 状态导致开发模式的时候没办法回调。

axios default has `accept: 'application/json'` header and vite will not redirect it to `index.html`.

_Originally posted by @yyx990803 in https://github.com/vitejs/vite/issues/1723#issuecomment-767569118_

主要问题是 vite 不会重定向到 index.html，最简单的解决办法就是请求路由手动加上一个 index.html
