### ISSUE TITLE
创建成功后无法显示

### ISSUE THREAD

**Issue by zzg19901210** [MangoTsing/vite-electron-quick#6]
你好，我使用 npx create-vite-electron ftv-pc创建成功后，系统运行正常。但是不显示内容，是啥原因导致。

**Comment by yigehaobb** [comment]
要 cd ftv-pc   进入你的目录 然后 yarn  然后yarn dev  刚才测试了可以启动的

**Comment by yigehaobb** [comment]
我测试是正常的啊 这个错误代码贴图上来 不然M大不知道哪里错误的啊

**Comment by yigehaobb** [comment]
![Snipaste_2021-02-16_21-27-57](https://user-images.githubusercontent.com/8196320/108069124-f48d2800-709d-11eb-9843-b9063d66158c.png)

把package.json  里面的vite版本改成"vite": "2.0.0-beta.60",  最新的beta70 不知道哪里又改动了 期待M大的更新

**Comment by yigehaobb** [comment]
beta61也是可以的 beta62 就不行了 不知道beta62 改了哪里  等MangoTsing更新吧

**Comment by MangoTsing** [comment]
一直回老家过年来着，看问题是CSP安全策略配置，vite使用了`new Function`这种electron警告的使用方式。因为index.html里面的配置，导致直接限制🚫掉正常功能，先删除掉meta的CSP，后续根据安全策略再优化一下配置。
