### ISSUE TITLE
npm run dev就报错

### ISSUE THREAD

**Issue by wuyingfeng1992** [MangoTsing/vite-electron-quick#7]

**Comment by yigehaobb** [comment]
我测试是正常的啊 这个错误具体代码贴图上来 不然M大不知道哪里错误的啊

**Comment by yigehaobb** [comment]
![Snipaste_2021-02-16_21-27-57](https://user-images.githubusercontent.com/8196320/108069124-f48d2800-709d-11eb-9843-b9063d66158c.png)

把package.json  里面的vite版本改成"vite": "2.0.0-beta.60",  最新的beta70 不知道哪里又改动了 期待M大的更新

**Comment by MangoTsing** [comment]
一直回老家过年来着，看问题是CSP安全策略配置，vite使用了`new Function`这种electron警告的使用方式。因为index.html里面的配置，导致直接限制🚫掉正常功能，先删除掉meta的CSP，后续根据安全策略再优化一下配置。同时感谢一下 @yigehaobb 帮助解决问题哈

**Comment by yigehaobb** [comment]
还是大佬牛逼 我就是小白 没事喜欢更新一下 还是M大厉害 分分钟解决问题
