### ISSUE TITLE
"element-plus": "latest",  是不是多了一个^

### ISSUE THREAD

**Issue by yigehaobb** [MangoTsing/vite-electron-quick#8]
package.json 里面"element-plus": "latest",  是不是多了一个^  
不然升级升级不了  yarn upgrade-interactive --latest
![iShot2021-02-19 17 14 35](https://user-images.githubusercontent.com/8196320/108484042-60f26c00-72d6-11eb-89c9-e6c0b1bb4b23.jpg)

**Comment by MangoTsing** [comment]
👍之前没注意到
